version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: mazer-postgres
    environment:
      POSTGRES_DB: mazer_security
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app-mazer:
    image: 'spring-mazer-template:1'
    build:
      context: .
    container_name: app-mazer
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/mazer_security
      DB_USERNAME: postgres
      DB_PASSWORD: root
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
