logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.level.net.guides=DEBUG

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Evita que Spring Boot intente ejecutar 'docker compose up' al iniciar.
spring.docker.compose.enabled=false
